name: film_tracker
description: Film tracker

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  sqflite: ^1.1.0
  path_provider: any
  rxdart: ^0.21.0

  redux: ^3.0.0
  flutter_redux: ^0.5.3

  intl: ^0.15.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  fonts:
    - family: Roboto Mono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
